package NewLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ISelector;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import java.util.Objects;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Account_Constraints extends BaseConstraintsDescriptor {
  public Account_Constraints() {
    super(CONCEPTS.Account$73);
  }

  public static class Balance_Property extends BasePropertyConstraintsDescriptor {
    public Balance_Property(ConstraintsDescriptor container) {
      super(PROPS.balance$LYhh, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:06f31464-a3b9-475c-942a-e516b15e210a(NewLanguage.constraints)", "7805689172541270616"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      if (propertyValue < 0) {
        return false;
      }
      return true;
    }
  }
  public static class AccountID_Property extends BasePropertyConstraintsDescriptor {
    public AccountID_Property(ConstraintsDescriptor container) {
      super(PROPS.accountID$LXNf, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castString(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:06f31464-a3b9-475c-942a-e516b15e210a(NewLanguage.constraints)", "7805689172541288392"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, final String propertyValue) {
      return Sequence.fromIterable(SNodeOperations.ofConcept(SNodeOperations.getAllSiblings(node, false), CONCEPTS.Account$73)).select(new ISelector<SNode, String>() {
        public String select(SNode it) {
          return SPropertyOperations.getString(it, PROPS.accountID$LXNf);
        }
      }).all(new IWhereFilter<String>() {
        public boolean accept(String it) {
          return !(Objects.equals(it, propertyValue));
        }
      });
      // for checking the uniqueness of the ID's
    }
  }
  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(PROPS.balance$LYhh, new Balance_Property(this));
    properties.put(PROPS.accountID$LXNf, new AccountID_Property(this));
    return properties;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Account$73 = MetaAdapterFactory.getConcept(0x1ae813028ade45f4L, 0xa93392ecb47fefa4L, 0x6c5360f23464a1c8L, "NewLanguage.structure.Account");
  }

  private static final class PROPS {
    /*package*/ static final SProperty balance$LYhh = MetaAdapterFactory.getProperty(0x1ae813028ade45f4L, 0xa93392ecb47fefa4L, 0x6c5360f23464a1c8L, 0x6c5360f23465b2c0L, "balance");
    /*package*/ static final SProperty accountID$LXNf = MetaAdapterFactory.getProperty(0x1ae813028ade45f4L, 0xa93392ecb47fefa4L, 0x6c5360f23464a1c8L, 0x6c5360f23465b2beL, "accountID");
  }
}
