package NewLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseConstraintsAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class ConstraintsAspectDescriptor extends BaseConstraintsAspectDescriptor {
  public ConstraintsAspectDescriptor() {
  }

  @Override
  public ConstraintsDescriptor getConstraints(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return new ATM_Constraints();
      case 1:
        return new Account_Constraints();
      case 2:
        return new Card_Constraints();
      case 3:
        return new Customer_Constraints();
      case 4:
        return new FinancialInstitution_Constraints();
      case 5:
        return new ServiceOffered_Constraints();
      default:
    }
    return new BaseConstraintsDescriptor(concept);
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x1ae813028ade45f4L, 0xa93392ecb47fefa4L, 0x6c5360f23464a1d4L), MetaIdFactory.conceptId(0x1ae813028ade45f4L, 0xa93392ecb47fefa4L, 0x6c5360f23464a1c8L), MetaIdFactory.conceptId(0x1ae813028ade45f4L, 0xa93392ecb47fefa4L, 0x6c5360f23464a1d5L), MetaIdFactory.conceptId(0x1ae813028ade45f4L, 0xa93392ecb47fefa4L, 0x6c5360f23464a1d3L), MetaIdFactory.conceptId(0x1ae813028ade45f4L, 0xa93392ecb47fefa4L, 0x6c5360f23464a1c4L), MetaIdFactory.conceptId(0x1ae813028ade45f4L, 0xa93392ecb47fefa4L, 0x6c5360f23464a1c6L)).seal();
}
