package NewLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class FinancialInstitution_Constraints extends BaseConstraintsDescriptor {
  public FinancialInstitution_Constraints() {
    super(CONCEPTS.FinancialInstitution$UW);
  }

  public static class TotalAssets_Property extends BasePropertyConstraintsDescriptor {
    public TotalAssets_Property(ConstraintsDescriptor container) {
      super(PROPS.totalAssets$GXCU, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:06f31464-a3b9-475c-942a-e516b15e210a(NewLanguage.constraints)", "7805689172545241929"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue > 0;
    }
  }
  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(PROPS.totalAssets$GXCU, new TotalAssets_Property(this));
    return properties;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept FinancialInstitution$UW = MetaAdapterFactory.getConcept(0x1ae813028ade45f4L, 0xa93392ecb47fefa4L, 0x6c5360f23464a1c4L, "NewLanguage.structure.FinancialInstitution");
  }

  private static final class PROPS {
    /*package*/ static final SProperty totalAssets$GXCU = MetaAdapterFactory.getProperty(0x1ae813028ade45f4L, 0xa93392ecb47fefa4L, 0x6c5360f23464a1c4L, 0x6c5360f23464a1f6L, "totalAssets");
  }
}
