package NewLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ServiceOffered_Constraints extends BaseConstraintsDescriptor {
  public ServiceOffered_Constraints() {
    super(CONCEPTS.ServiceOffered$65);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ServiceOffered$65 = MetaAdapterFactory.getConcept(0x1ae813028ade45f4L, 0xa93392ecb47fefa4L, 0x6c5360f23464a1c6L, "NewLanguage.structure.ServiceOffered");
  }
}
